version: "1.3.1"

turnstile:
  siteKey: ""
  secretKey: ""

endpoints:
  custom:
    - label: "Ollama"
      baseURL: "http://host.docker.internal:11434"
      apiKey: "ollama"
      models:
        default:
          - llama3
        llama3:
          label: "Llama 3"
