services:
  api:
    build: ./microservices-app/api
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=microservices
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - micro-net

  worker:
    build: ./microservices-app/worker
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=microservices
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - micro-net

  redis:
    image: redis:alpine
    networks:
      - micro-net

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=microservices
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - micro-net

volumes:
  pgdata:

networks:
  micro-net:
